"""Explicit source-wiring assertions for native branches not compiled by portable tests."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def read(name):return (root/'raw'/name).read_text()
checks=[]
def check(name,condition):
 checks.append({'check':name,'passed':bool(condition)})
 if not condition:raise AssertionError(name)
ui=read('include/Generator/QuickMenuUI.h');native=read('src/Generator/InGameQuickMenu.cpp');asset=read('src/Loader/DragonWildsAssetModLoader.cpp');live=read('src/Loader/LiveCloneAuthoring.inl');companions=read('src/Loader/HelpyItemCompanions.inl');catalog=read('src/Loader/QuickMenuCatalog.inl');metadata=read('include/Loader/AssetAuthoringMetadata.h');settings=read('include/Runtime/HelpySettings.h');spawn=read('src/Loader/SpawnTools.inl');schema=read('include/Generator/LoaderSchemas.h');store=read('include/Runtime/F2CatalogStore.h');dll=read('src/dllmain.cpp');helpy=read('plugins/helpy/HelpyPlugin.cpp')
check('download decision uses explicit tested policy','HelpyReferencePolicy::ShouldFetch' in catalog and 'g_helpyInitialReferenceAttempted,updateReference' in catalog)
check('saved metadata is diagnostics-only','int LoadSettings(bool diagnosticCatalogs)' in catalog and 'if(diagnosticCatalogs)if(auto doc=ReadSavedCache' in catalog)
check('normal refresh scans mounted runtime registry','(void)LoadSettings(full);' in catalog and 'try {ScanRegistry();}' in catalog)
check('normal refresh does not persist diagnostic cache','if(!cacheWritable||!fullScan)return;' in catalog[catalog.index('void SaveCache()'):catalog.index('void ScanRegistry()')])
check('initial attempt only recorded on start','if(waitingReference)g_helpyInitialReferenceAttempted=true;' in catalog)
check('cached reference entries reused before request gate',catalog.index('LoadEntries(*cached)')<catalog.index('HelpyReferencePolicy::ShouldFetch'))
check('successful reference survives write failure in memory','g_helpyReferenceMemory=nlohmann::json' in catalog and 'if(!cached&&g_helpyReferenceMemory)' in catalog)
check('new source settings omit expiring TTL','ReferenceCacheHours' not in store[store.index('inline json EncodeSources'):store.index('inline F2Catalog::Sources DecodeSources')])
check('legacy age does not force request','sources.referenceCacheHours=0' in store and 'Now()' not in store[store.index('inline bool ReferenceFresh'):])
check('explicit update routed to same job','UpdateHelpyReference' in native and 'UpdateHelpyReference' in spawn and 'updateReference' in catalog)
check('UI branding and settings','RUNESCHEMA HELPY' in ui and 'RuneSchema Helpy' in native and 'CollapsingHeader("RuneSchema Helpy")' in read('include/Generator/SpawnToolsPanel.h'))
check('old fixed F2 registration removed','Input::Key::F2' not in dll and 'Input::Key::F2' not in helpy and 'HelpyHotkeys::Active.load()' in helpy)
check('settings binding shares same source','HelpySettings::SetKey(key.name)' in read('include/Generator/SpawnToolsPanel.h') and 'HelpySettings::SetKey(command.name)' in native)
set_key=settings[settings.index('inline bool SetKey'):]
check('hotkey persisted before activation',set_key.index('config->Save()')<set_key.index('HelpyHotkeys::Active=key->code'))
check('bad configuration disables overwrites','Writable=false' in settings and 'if(!Writable)' in settings)
tick=native[native.index('void InGameQuickMenu::TickInputSafety()'):native.index('void InGameQuickMenu::EnsureInputHook()')]
check('rebind release observed even while Helpy closed',tick.index('HelpyHotkeys::ObserveRelease')<tick.index('if(!IsOpen())'))
check('active hotkey pass-through used','static_cast<WPARAM>(HelpyHotkeys::Active.load())' in native)
check('favs target rename','ReferencesDirectory()/"Helpy-favorites.json"' in native)
check('no repeated per-frame favorite IO','if(model.favoritesLoaded&&!model.favoritesDirty)return;' in native)
check('file/per-asset metadata merged',asset.count('PS::AssetMetadata::Read(')>=3 and 'normalizedProperties.erase("Modded")' in asset)
check('metadata bypasses native writer','PS::AssetMetadata::IsKey(propertyName)' in asset)
check('canonical metadata keys declared',all(f'key=="{k}"' in metadata for k in ['RuneSchema','Cooked','SafeToClone']))
check('Yes/No legacy flags accepted',all(x in metadata for x in ['text=="yes"','text=="no"','value.is_boolean()']))
check('metadata schema root exceptions',all(x in schema for x in ['authorFlag','SafeToClone','^(?!(?:RuneSchema|Modded)$)']))
check('metadata registry and creation proof separate','PS::AssetMetadata::Record' in asset and 'PS::AssetProvenance::Record' in asset)
check('live source and donor permission checked',all(x in live for x in ['HelpyAllowClone(source,false)','HelpyAllowClone(source,permanent)','HelpyAllowClone(donor,true)']))
check('author declarations not cooked proof','VerifiedLoadedObject(object)' in companions and 'HasInstalledDefinition(object)' in companions)
check('runtime clone load order sorted','HelpyDependencies::Order' in asset and 'm_pendingAssets=std::move(sorted)' in asset)
check('incomplete runtime parent blocked','sourceOrigin.value("Registered",false)' in asset and 'AssetMetadata::IsIncomplete(source)' in asset)
check('typed rows routed to stat table envelope','HelpyStatKey::Parse(key)' in native and 'request["StatOverrides"]' in native)
check('raw format table then row','rawDocument[row->tableName][row->newRow]=row->values' in live)
check('new stat row checked before insertion','Stat row identity already exists' in live and 'row.table->AddRow' in live)
check('owned stats read back values','CloneValueMatches(check,v)' in live)
check('rollback removes owned row only','==row.installed)row.table->RemoveRow' in live)
check('source stat table never assigned new values','CopyJsonValueToContainer(value.GetData()' in live and 'CopyJsonValueToContainer(row.installed' not in live)
check('ambiguous short table names refused','Stat table name is ambiguous for /raw' in companions and 'Ambiguous /recipes table name' in companions)
check('complex shared inline edits refused','inline shared-object edits are forbidden' in live)
check('safe typed mesh and icon override','CloneRequireCookedReferences(mesh)' in live and 'CloneValidateOverride(p,value)' in live)
check('icon donor auto and source fallback',all(x in live for x in ['iconMode=="Auto"','iconMode=="Appearance"','iconSource=HelpyResolve(appearance)']))
check('journal native page descriptions','"PageDescriptions",nlohmann::json::array({{{"Description",description}}})' in companions)
check('journal links created item','{"JournalItemData",target}' in companions)
check('grouped journal requires IDs and names','Grouped journal entries need group ID and display name' in companions)
check('recipe uses existing Properties and AddTo wrappers',all(x in companions for x in ['"Properties",{{"ItemsConsumed",ingredients}','"ItemsCreated",nlohmann::json::array','"AddTo",nlohmann::json::array({placement})']))
check('recipe station derives native table shape','HelpyRecipeArrays' in companions and '"LabeledRecipes"' in companions and 'TEXT("Collection")' in companions)
check('companion outputs permanent only','Companion files require a permanent asset' in live)
check('publication coordinator tested and used','HelpyBundlePublish::Publish' in live)
check('raw published before asset',live.index('filename()=="raw")order.push_back')<live.index('order.push_back(file.get())'))
check('native rollback ends before publication',live.index('Clone registry rollback could not be verified')<live.index('HelpyBundlePublish::Publish'))
check('file failure quarantines and preserves pending','AssetMetadata::MarkIncomplete(created)' in live and 'document->PreservePending()' in live and '"PendingFiles",pendingFiles' in live)
check('no grant on incomplete bundle','BlockedCompanions' in spawn and 'CreatedFilesIncomplete' in spawn and 'AssetMetadata::IsIncomplete(item)' in spawn)
check('companion restart need disclosed','CompanionsNeedRestart' in live and 'CompanionsNeedRestart' in spawn)
check('both dimensions combine before pagination','HelpyItemFilters::Type' in ui and 'HelpyItemFilters::Source' in ui and '!ItemPasses(e,true)' in ui and '!ItemPasses(e,false)' in ui)
check('draft pending edits blocked','Wait for the pending item operation.' in ui and 'if(busy&&focus!=' in ui)
check('32 session draft limit','drafts.size()>=32' in ui and 'At most 32 item drafts per session.' in ui)
check('ingredients and icon use shared placards','ingredientPicker?"ingredient-item":iconPicker?"icon-item"' in ui)
check('single-player clone restriction retained','PS::Network::Detect(world).Mode!=PS::Network::Role::Standalone' in spawn)
check('recipe flow renders native item icons','icon(e->icon' in ui and 'for(std::size_t n=0;n<recipe.ingredients.size()&&n<5;++n)' in ui and 'recipe.station.icon' in ui)
check('quest tracker is a shallow overlay','questTrackerOpen' in ui and 'RUNESCHEMA QUEST TRACKER' in ui and 'quest-tracker' in ui)
check('quest controls use authority backend','QuestStatusRequests::Submit' in native and 'QuestAction' in ui)
check('quest controls reuse validated actions','RunQuestAction(binding,target,current)' in read('src/Loader/DragonWildsNpcLoader.cpp'))
check('repeat action respects repeat readiness','RepeatReady' in read('src/Loader/DragonWildsNpcLoader.cpp') and 'q.repeatable&&q.repeatReady' in ui)
check('players loader remains out of scope',not (root/'raw/src/Loader/DragonWildsPlayerLoader.cpp').exists())
(root/'verification/source-checks-v10-helpy.json').write_text(json.dumps(checks,indent=2)+'\n')
print(f'PASS: {len(checks)} Helpy native/source-wiring assertions (static only, not compilation).')
