// Offline capture of the shipped UI model. Fixture metadata and icon placeholders only.
#define main HelpyV9TestMain
#include "HelpyV9Tests.cpp"
#undef main
void dumpFrame(const Frame& f,const std::string& name){std::ofstream out(name+".draws");constexpr char h[]="0123456789abcdef";for(const auto& d:f.draws){out<<int(d.kind)<<'|'<<d.box.x<<'|'<<d.box.y<<'|'<<d.box.w<<'|'<<d.box.h<<'|'<<d.font<<'|'<<d.centreX;for(auto c:d.color)out<<'|'<<c;out<<'|';for(unsigned char c:d.text)out<<h[c>>4]<<h[c&15];out<<'|';for(unsigned char c:d.fallback)out<<h[c>>4]<<h[c&15];out<<'\n';}}
int main(){auto m=model();m.status="Saved reference index in use. No download required.";m.indexStage="Local catalogue ready";m.indexFinished=true;m.indexHasTotal=true;m.indexDone=m.indexTotal=40;
 const char* names[]{"Bronze Sword","Adventurer's Cape","Ash Logs","Iron Ore","Clean Water","Ghostly Cape","Nature Rune","Maple Logs","Quest Relic","Leather Boots","Healing Potion","Steel Sword"};
 auto c=m.catalog;for(std::size_t i=0;i<c.entries[0].size();++i)c.entries[0][i].name=names[i%12];c.entries[0][5].runeSchemaManaged=true;c.entries[0][5].declaredModded=true;c.entries[0][10].consumable=true;c.entries[0][8].quest=true;c.entries[0][11].masterwork=true;m.Update(c);m.ToggleFavorite(entry(5).path);
 dumpFrame(m.Render(),"01-items");m.Activate("item-filter-type");dumpFrame(m.Render(),"02-type-filter");m.Back();m.Activate("item-filter-source");dumpFrame(m.Render(),"03-source-filter");m.Back();
 m.Activate("item-subtab","clone");m.NewDraft();inspect(m);m.cloneName="Spectral Knight's Cape";m.cloneFlavour="A weathered cloak, still carrying an oath its wearer never broke.";m.clonePower="5";m.cloneSourceInfo.name="Adventurer's Cape";m.cloneAppearanceReady=true;m.cloneAppearanceInfo=entry(5);m.cloneAppearanceInfo.name="Ghostly Cape";m.cloneAppearance=m.cloneAppearanceInfo.path;m.appearanceMode=Model::Appearance::Copy;m.iconMode=Model::IconMode::Auto;m.cloneAcknowledged=true;
 dumpFrame(m.Render(),"04-item-editor");m.Activate("clone-advanced");m.Activate("clone-add-field");dumpFrame(m.Render(),"05-property-picker");m.Activate("clone-field","FlavourText");m.cloneValue="A weathered cloak, still carrying an oath its wearer never broke.\n\nThe threads shimmer softly in the dark.\nThis is editable flavour text, not a game screenshot.";m.caret=m.cloneValue.size();dumpFrame(m.Render(),"06-text-editor");m.Activate("clone-apply");m.Back();m.Activate("clone-companions");m.makeJournal=m.makeRecipe=true;m.journalTarget.name="Lore / Helpy Items";m.journalTarget.path="/Game/Example/Category.Category";m.journalTarget.grouped=true;m.journalGroup="Helpy";m.journalGroupName="Helpy Items";dumpFrame(m.Render(),"07-companions");
 m.Activate("recipe-edit");m.recipeStation.name="Example Smithing Station";m.recipeStation.path="/Game/Example/DT_Stations.DT_Stations";m.recipeStation.row="Example";m.ingredients={{entry(2).path,"Example metal bar",entry(2).icon,"8"},{entry(3).path,"Example thread",entry(3).icon,"4"}};dumpFrame(m.Render(),"08-recipe");m.Back();m.Back();m.Back();dumpFrame(m.Render(),"09-drafts");m.Activate("helpy-settings");dumpFrame(m.Render(),"10-settings");return 0;}
