"""Static source wiring checks, not a Windows build or live-host filesystem test."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
read=lambda p:(root/'raw'/p).read_text()
code=read('src/Loader/QuickMenuCatalog.inl')
store=read('include/Runtime/F2CatalogStore.h')
io=read('include/Runtime/F2PreferenceFile.h')
migration=read('include/Runtime/F2CacheMigration.h')
checks=[]
def check(name,value):
    checks.append({'check':name,'passed':bool(value)})
    if not value:raise AssertionError(name)
check('indexer no longer uses RuntimeDirectory', 'RuntimeDirectory()' not in code)
check('editable sources live in saved references','const auto references=PS::HostServices::ReferencesDirectory();' in code and 'references/"Helpy-catalog-sources.json"' in code)
check('user indexes live in saved references','const auto user=references/file;' in code and all(x in code for x in ['Helpy-catalog-index.json','Helpy-resource-index.json']))
check('generated local cache uses saved cache','const auto cache=PS::HostServices::CacheDirectory()/"Helpy-catalog-cache.json";' in code)
check('local cache read migrates if needed','ReadSavedCache(cache,PS::HostServices::SettingsDirectory()/"F2-catalog-cache.json")' in code)
check('reference cache read migrates if needed','ReadSavedCache(referenceFile,PS::HostServices::SettingsDirectory()/"F2-reference-index.json")' in code)
check('local cache writes to saved cache','Write(PS::HostServices::CacheDirectory()/"Helpy-catalog-cache.json"' in code)
check('reference cache writes to saved references','Write(PS::HostServices::ReferencesDirectory()/"Helpy-reference-index.json",*g_helpyReferenceMemory)' in code)
check('reference diagnostics use saved references','const auto referenceFile=PS::HostServices::ReferencesDirectory()/"Helpy-reference-index.json";' in code)
check('legacy settings are read only as compatibility sources','SettingsDirectory()/"F2-catalog-cache.json"' in code)
check('current paths never depend on selected mod','HostServices::CacheDirectory()' in code and 'HostServices::ReferencesDirectory()' in code)
check('reference write protected after read failure','referenceCacheWritable=false;partial=true;Issue(referenceFile.string(),e.what());' in code and 'if(!referenceCacheWritable)' in code)
check('migration success reports actual target path','imported saved data: {}' in code)
check('migration parses staged and current data with production codec','auto document=Read(path)' in store and 'DecodeEntries(*document,errors)' in store and 'if(!validated(staging))' in store and 'return validated(current)' in store)
check('bad cache records reject migration','if(!errors.empty())throw std::runtime_error("Invalid F2 cache:' in store)
check('existing settings copy wins','exists(current))return Result::CurrentExists' in migration)
check('migration always uses create-only publish','maxBytes,F2PreferenceFile::WriteMode::CreateOnly' in migration)
check('migration byte readback preserved','*verified!=*previous' in migration)
check('migration never deletes legacy','remove(legacy)' not in migration and 'rename(legacy' not in migration)
check('migration does not read content mod directories','/"mods"' not in migration and '/"mods"' not in code)
check('default preference write mode unchanged','WriteMode mode=WriteMode::ReplaceExisting' in io)
check('Windows create-only publication omits replace flag','mode==WriteMode::CreateOnly ? MOVEFILE_WRITE_THROUGH' in io)
check('POSIX create-only publication uses exclusive link','::link(staging.c_str(),file.c_str())' in io)
check('favorites stored under saved references','ReferencesDirectory()/"Helpy-favorites.json"' in read('src/Generator/InGameQuickMenu.cpp'))
check('old favorites import is retained','LoadWithLegacy(file,HostServices::SettingsDirectory()/"F2-favorites.json"' in read('src/Generator/InGameQuickMenu.cpp'))
check('authored mod output unchanged','HostServices::ModDirectory()/"mods"/"runeschema"/value' in read('include/Runtime/AuthoredFile.h'))
check('no BAT included in source overlay',not list((root/'raw').rglob('*.bat')))
(root/'verification/source-checks-v10-settings.json').write_text(json.dumps(checks,indent=2)+'\n')
print(f'PASS: {len(checks)} settings/migration source-wiring checks (static only).')
