"""Static integration checks. Passing is not native compilation or runtime validation."""
from pathlib import Path
import re,json
root=Path(__file__).resolve().parents[1]
files={str(p.relative_to(root)).replace('\\','/'):p.read_text(encoding='utf-8') for p in (root/'raw').rglob('*') if p.is_file()}
checks=[]
def check(name,condition):
    checks.append({'check':name,'passed':bool(condition)})
    if not condition:raise AssertionError(name)
ui=files['raw/include/Generator/QuickMenuUI.h'];native=files['raw/src/Generator/InGameQuickMenu.cpp'];catalog=files['raw/src/Loader/QuickMenuCatalog.inl'];tools=files['raw/include/Generator/ToolRequest.h'];spawn=files['raw/src/Loader/SpawnTools.inl'];spawnLoader=files['raw/src/Loader/DragonWildsSpawnLoader.cpp'];assets=files['raw/src/Generator/AssetSearch.cpp'];cooked=files['raw/include/SDK/Helper/CookedAssetLookup.h'];live=files['raw/src/Loader/LiveCloneAuthoring.inl'];deco=files['raw/include/Generator/QuickMenuDecorations.h'];store=files['raw/include/Runtime/F2FavoriteStore.h'];io=files['raw/include/Runtime/F2PreferenceFile.h'];placementDraft=files['raw/include/Loader/SpawnPlacementDraft.h'];config=files['raw/include/Utility/Config.h'];dllmain=files['raw/src/dllmain.cpp']
helpy=(root/'raw/plugins/helpy/HelpyPlugin.cpp').read_text(encoding='utf-8')
helpy_settings=(root/'raw/include/Runtime/HelpySettings.h').read_text(encoding='utf-8')
check('Helpy settings are plugin owned','pluginRoot/"settings"/"settings.jsonc"' in helpy_settings and 'PSConfig::Get()' not in helpy_settings)
check('Helpy plugin installs its own F2 lifecycle','HelpySettings::IsEnabled()' in helpy and 'RegisterEngineTickPostCallback' in helpy)
check('persistent RuneSchema actor identity is mod-and-entry owned','"{}|actor|{}", RC::to_string(spawn.ModName), entryId' in spawnLoader and 'spawn.StableId = StableActorGuid(identity)' in spawnLoader)
check('orphan sweep is limited to RuneSchema GUID marker','if (!HasActorGuidMagic(guid))' in spawnLoader and 'entry.Type == ESpawnEntryType::Actor' in spawnLoader)
check('orphan cleanup scans once per authoritative world','if (!world || m_orphanSweepComplete)' in spawnLoader and 'm_orphanSweepComplete = true;' in spawnLoader and 'm_orphanSweepComplete = false;' in spawnLoader)
for name in ['Dragonwilds','Runeschema','Favorite','Modded']:
 check('exact badge '+name,f'/RuneSchema/UI/Icons/Badges/T_Badge_{name}.T_Badge_{name}' in deco)
for name,asset in {'Vendor':'Vendor','QuestGiver':'Quest_Giver','NPC':'NPC','Lore':'Lore','Dialogue':'Dialogue'}.items():
 check('NPC role badge '+name,f'/RuneSchema/UI/Icons/Badges/T_Badge_{asset}.T_Badge_{asset}' in deco)
check('full scan badge path','/RuneSchema/UI/Icons/Badges/T_Badge_Full_Scan.T_Badge_Full_Scan' in deco)
check('exact identity component','/RuneSchema/Networking/BPC_RuneSchemaIdentity.BPC_RuneSchemaIdentity_C' in files['raw/include/Loader/NpcIdentityPayload.h'])
check('exact vanilla default banner','/Game/Art/UI/Craft/T_DeathShop_Banner.T_DeathShop_Banner' in files['raw/include/Loader/NpcCatalog.h'])
check('native crafting tab icons from FModel',all(path in files['raw/src/Loader/NpcNativeShopRefresh.inl'] for path in ['/Game/Art/UI/Craft/T_Icon_Craft_Normal.T_Icon_Craft_Normal','/Game/Art/UI/Craft/T_Icon_Craft_Highlight.T_Icon_Craft_Highlight','/Game/Art/UI/Craft/T_Icon_Repair_Normal.T_Icon_Repair_Normal','/Game/Art/UI/Craft/T_Icon_Repair_Highlight.T_Icon_Repair_Highlight','/Game/Art/UI/Craft/T_Icon_Ascend_Normal.T_Icon_Ascend_Normal','/Game/Art/UI/Craft/T_Icon_Ascend_Highlight.T_Icon_Ascend_Highlight']) and 'PrepareClientShopTabAssets(station)' in files['raw/src/Loader/DragonWildsNpcLoader.cpp'])
check('no bad badge aliases',all('T_Bade_' not in v for v in files.values()))
check('new cooked UI roots','BadgeRoot="/RuneSchema/UI/Icons/Badges/"' in deco and 'BannerRoot="/Game/Mods/RuneSchema/UI/Icons/Banners/"' in deco)
check('native power badge contract','/Game/Art/UI/PowerLevel/T_PowerLevel_NeutralZone.T_PowerLevel_NeutralZone' in deco and 'PowerBadgeRoot' not in deco and 'T_Power_' not in deco)
check('badge backing rectangles removed','badgePlate' not in ui and 'badgeShade' not in ui)
check('legacy badge compatibility','LowercaseBadgeRoot="/RuneSchema/UI/Icons/badges/"' in deco and 'PreviousBadgeRoot="/Game/RuneSchema/Badges/Runtime/"' in deco and 'LegacyBadgeRoot="/Game/Mods/RuneSchema/Badges/Runtime/"' in deco and 'FallbackTextures' in deco and 'FallbackTextures(draw.text)' in native)
check('correct UObject default unwrap', 'GetClassDefaultObject().Get();' in catalog)
check('enum CastField hotfix retained','PropertyHelper::CastProperty<FEnumProperty>(p)' in live and 'CastField<FEnumProperty>' not in live)
check('no forwarding numeric include','FNumericProperty.hpp' not in native and '<Unreal/CoreUObject/UObject/UnrealType.hpp>' in native)
check('actual badge draw tint','DrawTexture(canvas,texture,x+r.x*factor,y+r.y*factor,r.w*factor,r.h*factor,c[0],c[1],c[2],c[3])' in native)
check('missing texture readable fallback','draw.kind==QuickUI::Draw::Kind::Badge?draw.fallback' in native and 'if(!drawn)' in native)
check('texture type validation','texture->IsA(textureType)' in native)
check('one texture resolve per frame','!loadedIcon&&!m_failedCanvasIcons.contains(draw.text)' in native)
check('retry after refresh','m_failedCanvasIcons.clear()' in native)
check('icon-only versionless header','badge(QuickDecorations::RuneSchemaBadge,{20,10,40,40},"RS")' in ui and 'text("RuneSchema",' not in ui)
check('12 cards per page','ItemsPerPage=12' in ui)
check('shared placard drawing','const auto placard=' in ui and 'GridX+(slot%Columns)*CardPitchX' in ui)
check('favorite art and hitbox constants','FavoriteHitSize=36.f' in deco and 'BadgeSize=24.f' in deco)
check('favorite hit appended after card','f.hits.push_back({hit,"favorite",e.path})' in ui)
check('favorites display page','"item-subtab","favorites"' in ui)
check('cooked donor filter','cooked&&!e.cooked' in ui)
check('read-only missing favorites','e.available=false;e.detail="Unavailable' in ui)
check('favorites moved with legacy import','ReferencesDirectory()/"Helpy-favorites.json"' in native and 'LoadWithLegacy(file,HostServices::SettingsDirectory()/"F2-favorites.json"' in native)
check('favorites sync before and after events',native.count('SyncFavorites(m_ui)')==2)
check('corrupt file is not overwritten','model.favoritesWritable=false' in native and 'if(!model.favoritesWritable)return;' in native)
check('preference file exclusive staging','CREATE_NEW' in io and 'O_WRONLY|O_CREAT|O_EXCL' in io)
check('Windows flush and replace','FlushFileBuffers' in io and 'MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH' in io)
check('bounded preference input','MaxBytes=1024*1024' in io and 'file_size(file)>maxBytes' in io)
check('readback compares favorite records','if(Load(staging)!=records)' in store)
check('JSON version and structure checked','document["Version"]!=1' in store and 'document["Favorites"].is_array()' in store)
check('JSON nesting bound','depth>8' in store)
check('exact clone provenance','"RuneSchemaAssetClone"' in assets and 'provenance.value("Confirmed",false)' in assets)
check('no quality from power','const bool masterwork=QuickDecorations::Token(tags,"masterwork")||ItemBool' in assets)
check('native category icon','ReferencePath(object,"CategoryClassIcon")' in assets)
check('metadata reaches GUI',all(f'row.value("{k}"' in native for k in ['RuntimeClone','Masterwork','Consumable','QuestItem','CategoryIcon']))
check('search hint independent slot','std::optional<std::string> SearchHint' in tools and 'TakeSearchHint' in tools)
check('obsolete hints cancelled on clear','Pending.reset();SearchHint.reset();' in tools)
check('bounded debounce','milliseconds(300)' in native and 'query.size()>=2' in native)
check('bounded priority queue','priority.size()==48' in files['raw/include/Generator/F2CatalogPlan.h'])
check('copied path candidate queue','PS::F2Catalog::Plan plan' in catalog and 'Add({package+"."+name,name,Kind::Item})' in catalog)
check('game-thread priority pump','TakeSearchHint()' in spawn and 'g_quickCatalogIndex.Prioritize' in spawn)
check('priority keeps mutation receipts','CatalogProgress(Snapshot(referenceStatus,lists))' in catalog and 'static void CatalogProgress' in tools)
check('new clone refreshes roster','Refresh Helpy to update item placards.' in spawn)
check('spawn drafts resolve authoring $z on export','StageGroundDraft' in spawn and 'ResolveGroundDrafts(m_toolPlacements)' in spawn and 'placement["$z"]=resolvedZ' in placementDraft and 'placement.erase("$z")' in placementDraft)
check('spawn draft namespace remains global',spawnLoader.index('#include "Loader/SpawnPlacementDraft.h"') < spawnLoader.index('namespace DragonWilds {') and 'SpawnPlacementDraft.h' not in spawn)
check('Helpy NPCs use shared $z placement','d.GroundToSurface=true;d.GroundOffset=100' in files['raw/src/Loader/HelpyNpcAuthoring.inl'] and '{"Z","$+100"}' in files['raw/src/Loader/HelpyNpcAuthoring.inl'])
check('quest event spawns use grounded event runtime','target.EventKey.empty()' in files['raw/include/Loader/QuestDefinition.h'] and 'if(member.Ground)' in files['raw/include/Loader/EventRuntime.h'] and 'item.Ground=true' in files['raw/include/Loader/EventDefinition.h'])
check('known runtime provenance disallows cooked fallback','"RuneSchemaAssetClone"' in cooked and 'RF_WasLoaded' in cooked)
check('registry miss still denied','if(Available())return ContainsReference(path);' in cooked)
check('source and create share eligibility checks',all(x in live for x in ['HelpyAllowClone(source,false)','HelpyAllowClone(source,permanent)']) and 'VerifiedLoadedObject(object)' in files['raw/src/Loader/HelpyItemCompanions.inl'])
check('item lab separates raw stats','cloneRawFields' in ui and 'RAW STATS' in ui and 'permanent /raw companion' in ui and 'request["StatOverrides"]' in native and 'StagedFile>("raw"' in live)
check('changed quests receive targeted clean reset','ResetForDefinitionChange' in files['raw/include/Loader/QuestNativeAdapter.h'] and 'else if(resetChanged){resetChanged();ResetFresh();}' in files['raw/include/Loader/QuestReceiptJournal.h'] and 'api.ResetForDefinitionChange()' in files['raw/include/Loader/NativeQuestReceipt.h'])
check('appearance donor uses same proof','VerifiedLoadedObject(donor)' in live)
check('appearance reference fallback verifies actual object','VerifiedLoadedObject(asset)' in live)
check('raw/TObjectPtr outer accessor handled','if constexpr(requires {pointer.Get();})' in cooked)
check('no build script included in source overlay',not list((root/'raw').rglob('*.bat')))
index=files['raw/src/Runtime/F2ReferenceIndex.cpp'];plan=files['raw/include/Generator/F2CatalogPlan.h'];schema=files['raw/include/Generator/LoaderSchemas.h'];provenance=files['raw/src/Loader/AssetProvenance.cpp'];assetLoader=files['raw/src/Loader/DragonWildsAssetModLoader.cpp']
check('refresh starts shared indexing','action=="QuickCatalog"||action=="IndexQuickCatalog"' in spawn and 'g_quickCatalogIndex.Start' in spawn)
check('coalesced refresh requests','if(g_quickCatalogIndex.active)' in spawn)
check('progress fields pass through queue',all('\"'+key+'\"' in tools and '\"'+key+'\"' in native for key in ['IndexStage','IndexDone','IndexTotal','IndexHasTotal','IndexFinished']))
check('native source-index worker is game-free','ActorHelper' not in index and 'UObject' not in index and 'std::async(std::launch::async' in index)
check('worker explicitly joined','g_f2ReferenceJob.Shutdown()' in files['raw/src/Loader/DragonWildsSpawnLoader.cpp'])
check('https fixed public reference host','L"api.github.com"' in index and 'WINHTTP_FLAG_SECURE' in index)
check('no HTTP redirects or automatic credentials','WINHTTP_DISABLE_REDIRECTS' in index and 'WINHTTP_AUTOLOGON_SECURITY_LEVEL_HIGH' in index)
check('bounded HTTP work','requests>80' in index and 'seconds(90)' in index and 'text.size()+read>24*1024*1024' in index)
check('truncated references split','if(tree.truncated)' in files['raw/include/Generator/F2ReferenceTree.h'])
check('refresh loads saved references and caches',all(k in catalog for k in ['Helpy-catalog-sources.json','Helpy-catalog-index.json','Helpy-reference-index.json','Helpy-catalog-cache.json']))
check('cached paths not spawn permission','Cached path; not yet validated in this world' in catalog and '{"Available",false}' in catalog)
check('world generation invalidates indexing','generation!=PS::SpawnToolRequests::Generation.load()' in catalog)
check('cancelled index does not resume on search','if(stopped||generation' in catalog)
check('current query applied to late index results','plan.Prioritize(searchQuery)' in catalog)
check('native UObject work on game-thread tick','while(attempted++<4)' in catalog and 'ActorHelper::ResolveObject' in catalog)
check('failed reference does not replace old file','if(reference->error.empty())' in catalog and 'existing cache retained' in index)
check('loaded clone creation tracked immediately','PS::AssetProvenance::Record(created,pendingAsset.Properties.at("$Clone")' in assetLoader)
check('provenance shares serial-assigned identity','PS::WeakObjectHandle handle' in provenance and 'created.handle.Assign(object)' in provenance and 'entry.handle.Get()!=object' in provenance)
check('no new origin from a patch','if(!createdNow)return' in provenance)
check('bSoftDeleted shared authoring recognition','name == "bSoftDeleted"' in files['raw/include/Generator/AuthoringPolicy.h'])
check('bSoftDeleted optional asset schema','asset["properties"]["bSoftDeleted"]' in schema)
check('bSoftDeleted generic captures','"BuffDatas","GrantedEffects","bSoftDeleted"' in assets)
check('missing string name fallback','QuickDecorations::MissingDisplayName(name)' in assets)
check('wheel no page navigation','void Wheel(int steps)' in ui and 'void Page(int steps)' in ui and 'Page(key==33?1:-1)' in ui)
check('narrow layout without shrinking fonts','Width=680' in ui and 'HorizontalFit=Width/DesignWidth' in ui)
check('unknown progress indeterminate','indexing&&!indexHasTotal' in ui)
check('numeric inputs centered','numeric?r.x+r.w/2' in ui)
check('selected player survives controller replacement','recipientName' in ui and 'if(p.name==recipientName)' in ui and 'if(match)recipient=match->id' in ui)
check('NPC relationships reach role badges',all(key in files['raw/src/Loader/HelpyNpcAuthoring.inl'] and f'row.value("{key}"' in native for key in ['Vendor','QuestGiver','Lore','Dialogue']) and all(name+'Badge' in ui for name in ['Vendor','QuestGiver','Lore','Dialogue','Npc']))
check('read-only item inspection precedes authority gate',spawn.index('if(action=="InspectClone")') < spawn.index('if(!selected)throw std::runtime_error("Selected authoritative player is unavailable; refresh")') and 'Player selection is only required for inventory actions.' in spawn and 'if(action=="CreateClone")' in spawn)
check('incomplete clones remain unavailable','"Available",!AssetMetadata::IsIncomplete(object)&&(!runtimeClone||provenance.value("Registered",false))' in assets and 'row["Available"]=row.value("Available",true)' in catalog)
check('failed startup stops its job','g_quickCatalogIndex.Stop("Refresh could not start;' in spawn)
output=root/'verification/source-checks-v10.json' ;output.write_text(json.dumps(checks,indent=2)+'\n')
print(f'PASS: {len(checks)} static integration checks; not native compilation.')
